package com.cabletech.station.beans;

// default package

import java.util.Date;

import com.cabletech.commons.base.BaseBean;

/**
 * PlanPatrolResultDay generated by MyEclipse Persistence Tools
 */

public class PlanPatrolResultBean extends BaseBean {

    // Fields

    private String tid;

    private String repeaterStationId;

    private String simId;

    private String patrolDate;

    private String createDate;

    private String patrolmanName;

    private String terminalTemperature;

    private String terminalHumidity;

    private String machineClean;

    private String topPilotLamp;

    private String veneerPilotLamp;

    private String termialSurfaceTemperature;

    private String batterylVoltage;

    private String isDdfLoosen;

    private String isOdfLoosen;

    private String deviceFanStateCheckClean;

    private String cabinetFuseAlarmCheck;

    private String terminalSurfaceClean;

    private String rackClean;

    private String distributionFrameClean;

    private String solarEnergyClean;

    private String batteryCapacitance;

    private String resistancetestTest;

    private String machineResistancetestTest;

    private String powerLineTest;

    private String earthLineTest;

    private String patrolRemark;

    private String planId;

    // Constructors

    /** default constructor */
    public PlanPatrolResultBean() {
    }

    /** minimal constructor */
    public PlanPatrolResultBean(String tid) {
        this.tid = tid;
    }

    /** full constructor */
    public PlanPatrolResultBean(String tid, String repeaterStationId, String simId,
            String patrolDate, String patrolmanName, String terminalTemperature,
            String terminalHumidity, String machineClean, String topPilotLamp,
            String veneerPilotLamp, String termialSurfaceTemperature, String batterylVoltage,
            String patrolRemark, String planId) {
        this.tid = tid;
        this.repeaterStationId = repeaterStationId;
        this.simId = simId;
        this.patrolDate = patrolDate;
        this.patrolmanName = patrolmanName;
        this.terminalTemperature = terminalTemperature;
        this.terminalHumidity = terminalHumidity;
        this.machineClean = machineClean;
        this.topPilotLamp = topPilotLamp;
        this.veneerPilotLamp = veneerPilotLamp;
        this.termialSurfaceTemperature = termialSurfaceTemperature;
        this.batterylVoltage = batterylVoltage;
        this.patrolRemark = patrolRemark;
        this.planId = planId;
    }

    // Property accessors

    public String getTid() {
        return this.tid;
    }

    public void setTid(String tid) {
        this.tid = tid;
    }

    public String getRepeaterStationId() {
        return this.repeaterStationId;
    }

    public void setRepeaterStationId(String repeaterStationId) {
        this.repeaterStationId = repeaterStationId;
    }

    public String getSimId() {
        return this.simId;
    }

    public void setSimId(String simId) {
        this.simId = simId;
    }

    public String getPatrolDate() {
        return this.patrolDate;
    }

    public void setPatrolDate(String patrolDate) {
        this.patrolDate = patrolDate;
    }

    public String getPatrolmanName() {
        return this.patrolmanName;
    }

    public void setPatrolmanName(String patrolmanName) {
        this.patrolmanName = patrolmanName;
    }

    public String getTerminalTemperature() {
        return this.terminalTemperature;
    }

    public void setTerminalTemperature(String terminalTemperature) {
        this.terminalTemperature = terminalTemperature;
    }

    public String getTerminalHumidity() {
        return this.terminalHumidity;
    }

    public void setTerminalHumidity(String terminalHumidity) {
        this.terminalHumidity = terminalHumidity;
    }

    public String getMachineClean() {
        return this.machineClean;
    }

    public void setMachineClean(String machineClean) {
        this.machineClean = machineClean;
    }

    public String getTopPilotLamp() {
        return this.topPilotLamp;
    }

    public void setTopPilotLamp(String topPilotLamp) {
        this.topPilotLamp = topPilotLamp;
    }

    public String getVeneerPilotLamp() {
        return this.veneerPilotLamp;
    }

    public void setVeneerPilotLamp(String veneerPilotLamp) {
        this.veneerPilotLamp = veneerPilotLamp;
    }

    public String getTermialSurfaceTemperature() {
        return this.termialSurfaceTemperature;
    }

    public void setTermialSurfaceTemperature(String termialSurfaceTemperature) {
        this.termialSurfaceTemperature = termialSurfaceTemperature;
    }

    public String getBatterylVoltage() {
        return this.batterylVoltage;
    }

    public void setBatterylVoltage(String batterylVoltage) {
        this.batterylVoltage = batterylVoltage;
    }

    public String getPatrolRemark() {
        return this.patrolRemark;
    }

    public void setPatrolRemark(String patrolRemark) {
        this.patrolRemark = patrolRemark;
    }

    public String getPlanId() {
        return this.planId;
    }

    public void setPlanId(String planId) {
        this.planId = planId;
    }

    public String getBatteryCapacitance() {
        return batteryCapacitance;
    }

    public void setBatteryCapacitance(String batteryCapacitance) {
        this.batteryCapacitance = batteryCapacitance;
    }

    public String getCabinetFuseAlarmCheck() {
        return cabinetFuseAlarmCheck;
    }

    public void setCabinetFuseAlarmCheck(String cabinetFuseAlarmCheck) {
        this.cabinetFuseAlarmCheck = cabinetFuseAlarmCheck;
    }

    public String getDeviceFanStateCheckClean() {
        return deviceFanStateCheckClean;
    }

    public void setDeviceFanStateCheckClean(String deviceFanStateCheckClean) {
        this.deviceFanStateCheckClean = deviceFanStateCheckClean;
    }

    public String getDistributionFrameClean() {
        return distributionFrameClean;
    }

    public void setDistributionFrameClean(String distributionFrameClean) {
        this.distributionFrameClean = distributionFrameClean;
    }

    public String getEarthLineTest() {
        return earthLineTest;
    }

    public void setEarthLineTest(String earthLineTest) {
        this.earthLineTest = earthLineTest;
    }

    public String getIsDdfLoosen() {
        return isDdfLoosen;
    }

    public void setIsDdfLoosen(String isDdfLoosen) {
        this.isDdfLoosen = isDdfLoosen;
    }

    public String getIsOdfLoosen() {
        return isOdfLoosen;
    }

    public void setIsOdfLoosen(String isOdfLoosen) {
        this.isOdfLoosen = isOdfLoosen;
    }

    public String getMachineResistancetestTest() {
        return machineResistancetestTest;
    }

    public void setMachineResistancetestTest(String machineResistancetestTest) {
        this.machineResistancetestTest = machineResistancetestTest;
    }

    public String getPowerLineTest() {
        return powerLineTest;
    }

    public void setPowerLineTest(String powerLineTest) {
        this.powerLineTest = powerLineTest;
    }

    public String getRackClean() {
        return rackClean;
    }

    public void setRackClean(String rackClean) {
        this.rackClean = rackClean;
    }

    public String getResistancetestTest() {
        return resistancetestTest;
    }

    public void setResistancetestTest(String resistancetestTest) {
        this.resistancetestTest = resistancetestTest;
    }

    public String getSolarEnergyClean() {
        return solarEnergyClean;
    }

    public void setSolarEnergyClean(String solarEnergyClean) {
        this.solarEnergyClean = solarEnergyClean;
    }

    public String getTerminalSurfaceClean() {
        return terminalSurfaceClean;
    }

    public void setTerminalSurfaceClean(String terminalSurfaceClean) {
        this.terminalSurfaceClean = terminalSurfaceClean;
    }

    public String getCreateDate() {
        return createDate;
    }

    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

}