package com.cabletech.station.beans;

// default package

import java.util.Date;

import com.cabletech.commons.base.BaseBean;

/**
 * RepeaterStationInfo generated by MyEclipse Persistence Tools
 */

public class RepeaterStationBean extends BaseBean {

    // Fields

    private String tid;

    private String regionId;

    private String stationName;

    private String isGroundStation;

    private String hasElectricity;

    private String connectElectricity;

    private String hasAirCondition;

    private String connectAirCondition;

    private String connectWindPowerGenerate;

    private Date createDate;

    private String stationRemark;

    // Constructors

    /** default constructor */
    public RepeaterStationBean() {
    }

    /** minimal constructor */
    public RepeaterStationBean(String tid) {
        this.tid = tid;
    }

    /** full constructor */
    public RepeaterStationBean(String tid, String regionId, String stationName,
            String isGroundStation, String hasElectricity, String connectElectricity,
            String hasAirCondition, String connectAirCondition, String connectWindPowerGenerate,
            Date createDate, String stationRemak) {
        this.tid = tid;
        this.regionId = regionId;
        this.stationName = stationName;
        this.isGroundStation = isGroundStation;
        this.hasElectricity = hasElectricity;
        this.connectElectricity = connectElectricity;
        this.hasAirCondition = hasAirCondition;
        this.connectAirCondition = connectAirCondition;
        this.connectWindPowerGenerate = connectWindPowerGenerate;
        this.createDate = createDate;
        this.stationRemark = stationRemak;
    }

    // Property accessors

    public String getTid() {
        return this.tid;
    }

    public void setTid(String tid) {
        this.tid = tid;
    }

    public String getRegionId() {
        return this.regionId;
    }

    public void setRegionId(String regionId) {
        this.regionId = regionId;
    }

    public String getStationName() {
        return this.stationName;
    }

    public void setStationName(String stationName) {
        this.stationName = stationName;
    }

    public String getIsGroundStation() {
        return this.isGroundStation;
    }

    public void setIsGroundStation(String isGroundStation) {
        this.isGroundStation = isGroundStation;
    }

    public String getHasElectricity() {
        return this.hasElectricity;
    }

    public void setHasElectricity(String hasElectricity) {
        this.hasElectricity = hasElectricity;
    }

    public String getConnectElectricity() {
        return this.connectElectricity;
    }

    public void setConnectElectricity(String connectElectricity) {
        this.connectElectricity = connectElectricity;
    }

    public String getHasAirCondition() {
        return this.hasAirCondition;
    }

    public void setHasAirCondition(String hasAirCondition) {
        this.hasAirCondition = hasAirCondition;
    }

    public String getConnectAirCondition() {
        return this.connectAirCondition;
    }

    public void setConnectAirCondition(String connectAirCondition) {
        this.connectAirCondition = connectAirCondition;
    }

    public String getConnectWindPowerGenerate() {
        return this.connectWindPowerGenerate;
    }

    public void setConnectWindPowerGenerate(String connectWindPowerGenerate) {
        this.connectWindPowerGenerate = connectWindPowerGenerate;
    }

    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public String getStationRemark() {
        return this.stationRemark;
    }

    public void setStationRemark(String stationRemak) {
        this.stationRemark = stationRemak;
    }

}