package com.cabletech.station.domainobjects;

// default package


/**
 * PlanPatrolResultMonth generated by MyEclipse Persistence Tools
 */

public class PlanPatrolResultMonth extends PlanPatrolResult {

    // Fields

    private String terminalSurfaceClean;

    private String rackClean;

    private String distributionFrameClean;

    private String solarEnergyClean;

    // Constructors

    /** default constructor */
    public PlanPatrolResultMonth() {
    }

    // Property accessors

    public String getTerminalSurfaceClean() {
        return this.terminalSurfaceClean;
    }

    public void setTerminalSurfaceClean(String terminalSurfaceClean) {
        this.terminalSurfaceClean = terminalSurfaceClean;
    }

    public String getRackClean() {
        return this.rackClean;
    }

    public void setRackClean(String rackClean) {
        this.rackClean = rackClean;
    }

    public String getDistributionFrameClean() {
        return this.distributionFrameClean;
    }

    public void setDistributionFrameClean(String distributionFrameClean) {
        this.distributionFrameClean = distributionFrameClean;
    }

    public String getSolarEnergyClean() {
        return this.solarEnergyClean;
    }

    public void setSolarEnergyClean(String solarEnergyClean) {
        this.solarEnergyClean = solarEnergyClean;
    }

}