package com.cabletech.station.domainobjects;

// default package

/**
 * PlanPatrolResultDay generated by MyEclipse Persistence Tools
 */

public class PlanPatrolResultDay extends PlanPatrolResult {

    // Fields

    private String terminalTemperature;

    private String terminalHumidity;

    private String machineClean;

    private String topPilotLamp;

    private String veneerPilotLamp;

    private String termialSurfaceTemperature;

    private String batterylVoltage;

    // Constructors

    /** default constructor */
    public PlanPatrolResultDay() {
    }

    // Property accessors

    public String getTerminalTemperature() {
        return this.terminalTemperature;
    }

    public void setTerminalTemperature(String terminalTemperature) {
        this.terminalTemperature = terminalTemperature;
    }

    public String getTerminalHumidity() {
        return this.terminalHumidity;
    }

    public void setTerminalHumidity(String terminalHumidity) {
        this.terminalHumidity = terminalHumidity;
    }

    public String getMachineClean() {
        return this.machineClean;
    }

    public void setMachineClean(String machineClean) {
        this.machineClean = machineClean;
    }

    public String getTopPilotLamp() {
        return this.topPilotLamp;
    }

    public void setTopPilotLamp(String topPilotLamp) {
        this.topPilotLamp = topPilotLamp;
    }

    public String getVeneerPilotLamp() {
        return this.veneerPilotLamp;
    }

    public void setVeneerPilotLamp(String veneerPilotLamp) {
        this.veneerPilotLamp = veneerPilotLamp;
    }

    public String getTermialSurfaceTemperature() {
        return this.termialSurfaceTemperature;
    }

    public void setTermialSurfaceTemperature(String termialSurfaceTemperature) {
        this.termialSurfaceTemperature = termialSurfaceTemperature;
    }

    public String getBatterylVoltage() {
        return this.batterylVoltage;
    }

    public void setBatterylVoltage(String batterylVoltage) {
        this.batterylVoltage = batterylVoltage;
    }

}