package com.cabletech.station.domainobjects;

// default package

import java.util.Date;

import com.cabletech.commons.base.BaseDomainObject;

/**
 * PlanPatrolResultDay generated by MyEclipse Persistence Tools
 */

public abstract class PlanPatrolResult extends BaseDomainObject {

    // Fields

    private String tid;

    private String repeaterStationId;

    private String simId;

    private Date patrolDate;

    private String patrolmanName;

    private String patrolRemark;

    private String planId;

    private Date createDate;

    // Constructors

    /** default constructor */
    public PlanPatrolResult() {
    }

    // Property accessors

    public String getTid() {
        return this.tid;
    }

    public void setTid(String tid) {
        this.tid = tid;
    }

    public String getRepeaterStationId() {
        return this.repeaterStationId;
    }

    public void setRepeaterStationId(String repeaterStationId) {
        this.repeaterStationId = repeaterStationId;
    }

    public String getSimId() {
        return this.simId;
    }

    public void setSimId(String simId) {
        this.simId = simId;
    }

    public Date getPatrolDate() {
        return this.patrolDate;
    }

    public void setPatrolDate(Date patrolDate) {
        this.patrolDate = patrolDate;
    }

    public String getPatrolmanName() {
        return this.patrolmanName;
    }

    public void setPatrolmanName(String patrolmanName) {
        this.patrolmanName = patrolmanName;
    }

    public String getPatrolRemark() {
        return this.patrolRemark;
    }

    public void setPatrolRemark(String patrolRemark) {
        this.patrolRemark = patrolRemark;
    }

    public String getPlanId() {
        return this.planId;
    }

    public void setPlanId(String planId) {
        this.planId = planId;
    }

    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

}