package com.cabletech.station.domainobjects;

// default package

import java.util.Date;

import com.cabletech.commons.base.BaseDomainObject;

/**
 * PlanPatrolResultWeek generated by MyEclipse Persistence Tools
 */

public class PlanPatrolResultWeek extends PlanPatrolResult {

    // Fields

    private String isDdfLoosen;

    private String isOdfLoosen;

    private String deviceFanStateCheckClean;

    private String cabinetFuseAlarmCheck;

    // Constructors

    /** default constructor */
    public PlanPatrolResultWeek() {
    }

    // Property accessors

    public String getIsDdfLoosen() {
        return this.isDdfLoosen;
    }

    public void setIsDdfLoosen(String isDdfLoosen) {
        this.isDdfLoosen = isDdfLoosen;
    }

    public String getIsOdfLoosen() {
        return this.isOdfLoosen;
    }

    public void setIsOdfLoosen(String isOdfLoosen) {
        this.isOdfLoosen = isOdfLoosen;
    }

    public String getDeviceFanStateCheckClean() {
        return this.deviceFanStateCheckClean;
    }

    public void setDeviceFanStateCheckClean(String deviceFanStateCheckClean) {
        this.deviceFanStateCheckClean = deviceFanStateCheckClean;
    }

    public String getCabinetFuseAlarmCheck() {
        return this.cabinetFuseAlarmCheck;
    }

    public void setCabinetFuseAlarmCheck(String cabinetFuseAlarmCheck) {
        this.cabinetFuseAlarmCheck = cabinetFuseAlarmCheck;
    }

}