package com.cabletech.station.domainobjects;

// default package

import java.util.Date;

import com.cabletech.commons.base.BaseDomainObject;

/**
 * RepeaterStationPlan generated by MyEclipse Persistence Tools
 */

public class RepeaterStationPlan extends BaseDomainObject {

    // Fields

    private String tid;

    private String regionId;

    private String planName;

    private Date beginDate;

    private Date endDate;

    private String planType;

    private String planState;

    private Date createDate;

    private String planRemark;

    private String validateResult;

    private String validateRemark;

    private String validateUserid;

    private Date validateTime;

    // Constructors

    /** default constructor */
    public RepeaterStationPlan() {
    }

    /** minimal constructor */
    public RepeaterStationPlan(String tid) {
        this.tid = tid;
    }

    /** full constructor */
    public RepeaterStationPlan(String tid, String regionId, String planName, Date beginDate,
            Date endDate, String planType, String planState, Date createDate, String planRemark,
            String validateResult, String validateRemark, String validateUserid, Date validateTime) {
        this.tid = tid;
        this.regionId = regionId;
        this.planName = planName;
        this.beginDate = beginDate;
        this.endDate = endDate;
        this.planType = planType;
        this.planState = planState;
        this.createDate = createDate;
        this.planRemark = planRemark;
        this.validateResult = validateResult;
        this.validateRemark = validateRemark;
        this.validateUserid = validateUserid;
        this.validateTime = validateTime;
    }

    // Property accessors

    public String getTid() {
        return this.tid;
    }

    public void setTid(String tid) {
        this.tid = tid;
    }

    public String getRegionId() {
        return this.regionId;
    }

    public void setRegionId(String regionId) {
        this.regionId = regionId;
    }

    public String getPlanName() {
        return this.planName;
    }

    public void setPlanName(String planName) {
        this.planName = planName;
    }

    public Date getBeginDate() {
        return this.beginDate;
    }

    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }

    public Date getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public String getPlanType() {
        return this.planType;
    }

    public void setPlanType(String planType) {
        this.planType = planType;
    }

    public String getPlanState() {
        return this.planState;
    }

    public void setPlanState(String planState) {
        this.planState = planState;
    }

    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public String getPlanRemark() {
        return this.planRemark;
    }

    public void setPlanRemark(String planRemark) {
        this.planRemark = planRemark;
    }

    public String getValidateResult() {
        return this.validateResult;
    }

    public void setValidateResult(String validateResult) {
        this.validateResult = validateResult;
    }

    public String getValidateRemark() {
        return this.validateRemark;
    }

    public void setValidateRemark(String validateRemark) {
        this.validateRemark = validateRemark;
    }

    public String getValidateUserid() {
        return this.validateUserid;
    }

    public void setValidateUserid(String validateUserid) {
        this.validateUserid = validateUserid;
    }

    public Date getValidateTime() {
        return this.validateTime;
    }

    public void setValidateTime(Date validateTime) {
        this.validateTime = validateTime;
    }

}