INSERT INTO LINECLASSDIC ( ID, CODE, NAME ) VALUES (
'0000000001', '1', '一干');
INSERT INTO LINECLASSDIC ( ID, CODE, NAME ) VALUES (
'0000000002', '2', '二干');
INSERT INTO LINECLASSDIC ( ID, CODE, NAME ) VALUES (
'0000000003', '3', '汇聚环');
INSERT INTO LINECLASSDIC ( ID, CODE, NAME ) VALUES (
'0000000004', '4', '接入网');
INSERT INTO LINECLASSDIC ( ID, CODE, NAME ) VALUES (
'0000000005', '5', '骨干层');
commit;
 set define off;
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'20304', '修改周计划', '203', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'20305', '删除周计划', '203', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'20404', '修改自定义计划', '204', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'20405', '删除自定义计划', '204', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'20104', '修改年计划', '201', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'20105', '删除年计划', '201', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'20204', '修改月计划', '202', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'20205', '删除月计划', '202', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'71202', '修改用户密码', '712', '/WebApp/baseinfo/validatePsw.jsp', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70904', '修改线路信息', '709', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70905', '删除线路信息', '709', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70204', '修改部门信息', '702', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70205', '删除部门信息', '702', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70504', '修改用户信息', '705', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70505', '删除用户信息', '705', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'71404', '修改巡检操作码', '714', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'71405', '删除巡检操作码', '714', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70604', '修改巡检维护组', '706', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70605', '删除巡检维护组', '706', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70804', '修改巡检设备', '708', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70805', '删除巡检设备', '708', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'71004', '修改巡检段信息', '710', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'71005', '删除巡检段信息', '710', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'71104', '修改巡检点信息', '711', NULL, NULL, '9');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'71105', '删除巡检点信息', '711', NULL, NULL, '9');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'71304', '修改事故码', '713', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'71305', '删除事故码', '713', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'71504', '修改报警号码', '715', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'71505', '删除报警号码', '715', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70304', '修改代维单位', '703', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70305', '删除代维单位', '703', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70704', '修改巡检员', '707', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70705', '删除巡检员', '707', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'20303', '高级查询', '203', '/WebApp/PlanAction.do?method=searchWPlanShow', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'20401', '查询自定义计划', '204', '/WebApp/PlanAction.do?method=queryCustomWPlan'
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'20402', '增加自定义计划', '204', '/WebApp/PlanAction.do?method=addWPlanShow&type=custom'
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'20403', '高级查询', '204', '/WebApp/PlanAction.do?method=searchWPlanShow&searchtype=custom'
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'20501', '巡检计划审批', '205', '/WebApp/YearMonthPlanAction.do?method=getUnapprovedYMPlan'
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'20601', '巡检明细查询', '206', '/WebApp/StatisticAction.do?method=showSearchPatrolDetail'
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'20701', '漏检明细查询', '207', '/WebApp/StatisticAction.do?method=showSearchPatrolloss'
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'20801', '计划巡检率', '208', '/WebApp/StatisticAction.do?method=showSearchPatrolRate'
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'20901', '计划审批通过率', '209', '/WebApp/SearchStatistic/QueryApproveRate.jsp', NULL
, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'21001', '计划汇总报表', '210', '/WebApp/StatisticAction.do?method=showNewQueryPlanForm'
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'21101', '盯防巡检明细', '211', '/WebApp/WatchManage/queryWatchexe.jsp', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'21201', '盯防巡检统计', '212', '/WebApp/WatchManage/queryWatchexeSta.jsp', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'40101', '盯防点信息', '401', '/WebApp/watchAction.do?method=queryTempWatch', NULL
, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'40102', '查询盯防点', '401', '/WebApp/WatchManage/queryTempWatchPoint.jsp', NULL
, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'40103', '制定盯防', '401', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'50101', '修缮查询', '501', '/WebApp/changeapplyaction.do?method=getApplyInfoList'
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'50102', '修缮填写', '501', '/WebApp/changeapplyaction.do?method=loadAddForm', NULL
, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'50601', '查看验收信息', '506', '/WebApp/checkaction.do?method=getCheckInfo', NULL
, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'60101', '待处理隐患', '601', '/WebApp/accidentAction.do?method=loadUndoenTrouble'
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'60102', '隐患查询', '601', '/WebApp/TroubleManage/queryTrouble.jsp', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'60201', '待处理障碍', '602', '/WebApp/accidentAction.do?method=loadUndoenAccident'
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'60202', '障碍查询', '602', '/WebApp/TroubleManage/queryAccident.jsp', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70101', '区域查询', '701', '/WebApp/regionAction.do?method=queryRegion&regionName='
, NULL, '');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70102', '增加区域', '701', '/WebApp/baseinfo/addRegion.jsp', NULL, '');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70103', '高级查询', '701', '/WebApp/baseinfo/queryRegion.jsp', NULL, '');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70201', '部门查询', '702', '/WebApp/departAction.do?method=queryDepart', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70202', '增加部门', '702', '/WebApp/baseinfo/addDepart.jsp', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70203', '高级查询', '702', '/WebApp/baseinfo/queryDepart.jsp', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70301', '查询代维单位', '703', '/WebApp/contractorAction.do?method=queryContractor&contractorName=&linkmanInfo='
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70302', '增加代维单位', '703', '/WebApp/baseinfo/addContractor.jsp', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70303', '高级查询', '703', '/WebApp/baseinfo/queryContractor.jsp', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70401', '用户组查询', '704', '/WebApp/UsergroupAction.do?method=getUserGroups', NULL
, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70402', '增加用户组', '704', '/WebApp/baseinfo/addUsergroup.jsp', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70501', '用户查询', '705', '/WebApp//userinfoAction.do?method=queryUserinfo&userName='
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70502', '增加用户', '705', '/WebApp/baseinfo/addUserInfo.jsp', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70503', '高级查询', '705', '/WebApp/baseinfo/queryUserInfo.jsp', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70601', '巡检维护组查询', '706', '/WebApp/patrolAction.do?method=queryPatrol', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70602', '增加巡检维护组', '706', '/WebApp/baseinfo/addPatrolMan.jsp', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70603', '高级查询', '706', '/WebApp/baseinfo/queryPatrolMan.jsp', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70701', '巡检员查询', '707', '/WebApp/patrolSonAction.do?method=queryPatrolSon', NULL
, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70702', '增加巡检员', '707', '/WebApp/baseinfo/addPatrolMan_son.jsp', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70703', '高级查询', '707', '/WebApp/baseinfo/queryPatrolMan_son.jsp', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70801', '查询移动设备', '708', '/WebApp/terminalAction.do?method=queryTerminal&produceMan=&terminalModel=&simNumber='
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70802', '增加移动设备', '708', '/WebApp/baseinfo/addTerminal.jsp', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70803', '高级查询', '708', '/WebApp/baseinfo/queryTerminal.jsp', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70901', '线路查询', '709', '/WebApp/lineAction.do?method=queryLine&lineName=', NULL
, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70902', '增加线路', '709', '/WebApp/baseinfo/addLine.jsp', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70903', '高级查询', '709', '/WebApp/baseinfo/queryLine.jsp', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'71001', '查询巡检线段', '710', '/WebApp/sublineAction.do?method=querySubline&subLineName='
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'71002', '增加巡检线段', '710', '/WebApp/sublineAction.do?method=loadSublineForm'
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'71003', '高级查询', '710', '/WebApp/sublineAction.do?method=loadQuerySublineForm'
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'71101', '查询巡检点', '711', '/WebApp/pointAction.do?method=queryPoint&pointName=&addressInfo='
, NULL, '9');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'71102', '增加巡检点', '711', NULL, NULL, '9');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'71201', '修改当前密码', '712', '/WebApp/SystemManage/updatePsw.jsp', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'71301', '查询事故代码', '713', '/WebApp/PatrolOpAction.do?method=queryPatrolOp&operationdes='
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'71302', '增加事故代码', '713', '/WebApp/baseinfo/addPatrolOp.jsp', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'71303', '高级查询', '713', '/WebApp/baseinfo/queryPatrolOp.jsp', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'71401', '查询巡检操作', '714', '/WebApp/TaskOperationAction.do?method=queryTaskOperation'
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'71402', '增加巡检操作', '714', '/WebApp/baseinfo/addTaskOperation.jsp', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'71403', '高级查询', '714', '/WebApp/baseinfo/queryTaskOperation.jsp', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'71501', '查询报警号码', '715', '/WebApp/AlertreceiverListAction.do?method=queryAlertreceiverList'
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'71502', '增加报警号码', '715', '/WebApp/baseinfo/addAlertreceiverList.jsp', NULL
, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'71503', '高级查询', '715', '/WebApp/baseinfo/queryAlertreceiverList.jsp', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'71601', '操作日志查询', '716', '/WebApp/SystemManage/querySysLog.jsp', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'71701', '短信接收日志', '717', '/WebApp/SystemManage/querySmsReciveLog.jsp', NULL
, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'71702', '短信发送日志', '717', '/WebApp/SystemManage/querySmsSendLog.jsp', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'71801', '当前在线用户', '718', '/WebApp/onlineuseraction.do?method=getOnlineUsers'
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'71901', '短信活动时段', '719', '/WebApp/SMSTimeAction.do?method=getTime', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'10101', '实时监控', '101', '/WebApp/frames/GIS_realTime/index_gis.jsp?cRegion=340100'
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'20101', '查询年计划', '201', '/WebApp/YearMonthPlanAction.do?method=queryYMPlan&fID=1&year='
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'20102', '增加年计划', '201', '/WebApp/planManage/addYearPlan.jsp', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'20103', '高级查询', '201', '/WebApp/planManage/searchYearPlan.jsp', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'20201', '查询月计划', '202', '/WebApp/YearMonthPlanAction.do?method=queryYMPlan&fID=2&year='
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'20202', '增加月计划', '202', '/WebApp/planManage/addMonthPlan.jsp', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'20203', '高级查询', '202', '/WebApp/planManage/searchMonthPlan.jsp', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'20301', '查询周计划', '203', '/WebApp/PlanAction.do?method=queryPlan', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'20302', '增加周计划', '203', '/WebApp/PlanAction.do?method=addWPlanShow', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'80401', '查看入库单', '804', '/WebApp/PartStockAction.do?method=dokShowStockInfo'
, NULL, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'80307', '使用统计', '803', '/WebApp/PartUseAction.do?method=queryShowForStat', NULL
, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'80306', '填写退库单', '803', '/WebApp/PartUseAction.do?method=showBackReason', NULL
, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'80101', '查看申请单', '801', '/WebApp/PartRequisitionAction.do?method=showAllRequisition'
, NULL, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'80102', '填写申请单', '801', '/WebApp/PartRequisitionAction.do?method=addReShow'
, NULL, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'80103', '查询申请单', '801', '/WebApp/PartRequisitionAction.do?method=queryShow'
, NULL, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'80104', '修改申请单', '801', NULL, NULL, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'80105', '删除申请单', '801', NULL, NULL, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'80201', '查看审批单', '802', '/WebApp/PartRequisitionAction.do?method=showAllAudit'
, NULL, '1');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'80202', '填写审批单', '802', '/WebApp/PartRequisitionAction.do?method=doAuditShow'
, NULL, '1');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'80203', '查询审批单', '802', '/WebApp/PartRequisitionAction.do?method=queryShowForAudit'
, NULL, '1');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'80301', '查看出库单', '803', '/WebApp/PartUseAction.do?method=showAllUse', NULL, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'80302', '填写出库单', '803', '/WebApp/PartUseAction.do?method=addUseShow', NULL, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'80303', '查询出库单', '803', '/WebApp/PartUseAction.do?method=queryShow', NULL, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'80402', '新材料入库', '804', '/WebApp/PartStockAction.do?method=doStockShow', NULL
, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'80403', '查询入库单', '804', '/WebApp/PartStockAction.do?method=queryShowForSrock'
, NULL, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'80501', '查看利旧入库单', '805', '/WebApp/PartStockAction.do?method=showAllOldStock'
, NULL, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'80502', '填写利旧入库单', '805', '/WebApp/PartStockAction.do?method=addOldShow', NULL
, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'80503', '查询利旧入库单', '805', '/WebApp/PartStockAction.do?method=queryShowForOldSrock'
, NULL, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'80601', '查看库存材料', '806', '/WebApp/PartStorageAction.do?method=showAllStorage'
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'80602', '处理库存', '806', '/WebApp/PartStorageAction.do?method=initStorageShow'
, NULL, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'80603', '查询库存', '806', '/WebApp/PartStorageAction.do?method=queryShow', NULL
, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'80701', '查看维护材料', '807', '/WebApp/PartBaseInfoAction.do?method=showPartBaseInfo'
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'40104', '取消盯防', '401', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'40207', '高级查询', '402', '/WebApp/WatchManage/queryWatch.jsp', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'80702', '添加维护材料', '807', '/WebApp/PartBaseInfoAction.do?method=addPartBaseInfoshow'
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'80703', '查询维护材料', '807', '/WebApp/PartBaseInfoAction.do?method=queryShow', NULL
, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'80704', '修改维护材料', '807', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'80705', '删除维护材料', '807', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'90101', '查看领用', '901', '/WebApp/ToolUseAction.do?method=showAllUse', NULL, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'90102', '领用备件', '901', '/WebApp/ToolUseAction.do?method=addUseShow', NULL, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'90103', '高级查询', '901', '/WebApp/ToolUseAction.do?method=queryShow', NULL, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'50301', '查看准备信息', '503', '/WebApp/buildsetoutaction.do?method=listBuildSetout'
, NULL, '1');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'50401', '查看委托信息', '504', '/WebApp/consignaction.do?method=listConsign', NULL
, '1');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'40203', '施工及核查', '402', '/WebApp/watchAction.do?method=loadAllDoneWatches', NULL
, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'90301', '查看报修', '903', '/WebApp/ToolMainAction.do?method=showAllMain', NULL, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'90302', '报修备件', '903', '/WebApp/ToolMainAction.do?method=addMainShow', NULL, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'90303', '高级查询', '903', '/WebApp/ToolMainAction.do?method=queryShow', NULL, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'90401', '查看送修', '904', '/WebApp/ToolToMainAction.do?method=showAllMain', NULL
, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'90402', '送修备件', '904', '/WebApp/ToolToMainAction.do?method=addMainShow', NULL
, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'90403', '高级查询', '904', '/WebApp/ToolToMainAction.do?method=queryShow', NULL, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'90407', '送修入库', '904', '/WebApp/ToolToMainAction.do?method=addMainBackShow', NULL
, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'90408', '送修报废', '904', '/WebApp/ToolToMainAction.do?method=addMainDeleShow', NULL
, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'90501', '查看入库', '905', '/WebApp/ToolStockAction.do?method=showAllStock', NULL
, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'90502', '备件入库', '905', '/WebApp/ToolStockAction.do?method=stockShow', NULL, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'90503', '高级查询', '905', '/WebApp/ToolStockAction.do?method=queryShow', NULL, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'90601', '查看报废', '906', '/WebApp/ToolStockAction.do?method=showAllRevoke', NULL
, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'90602', '报废备件', '906', '/WebApp/ToolStockAction.do?method=revokeShow', NULL, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'90603', '高级查询', '906', '/WebApp/ToolStockAction.do?method=queryShowForRevoke'
, NULL, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'90701', '查看库存', '907', '/WebApp/ToolStorageAction.do?method=showAllStorage', NULL
, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'90702', '修改库存', '907', '/WebApp/ToolStorageAction.do?method=initStorageShow'
, NULL, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'90703', '高级查询', '907', '/WebApp/ToolStorageAction.do?method=queryShow', NULL
, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'90801', '查看备件', '908', '/WebApp/ToolBaseAction.do?method=showToolsBaseInfo', NULL
, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'90802', '添加备件', '908', '/WebApp/ToolBaseAction.do?method=addToolsBaseInfoshow'
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'90803', '高级查询', '908', '/WebApp/ToolBaseAction.do?method=queryShow', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'90804', '修改备件', '908', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'90805', '删除备件', '908', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'40301', '统计查询', '403', '/WebApp/WatchManage/queryWatchexeSta.jsp', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'40201', '盯防信息', '402', '/WebApp/watchAction.do?method=queryWatch', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'40205', '修改', '402', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'50103', '高级查询', '501', '/WebApp/changeapplyaction.do?method=loadQueryForm', NULL
, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'50104', '修改修缮', '501', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'50105', '删除修缮', '501', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'50201', '查看勘查审定', '502', '/WebApp/changesurveyaction.do?method=getSurveyInfoList'
, NULL, '1');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'90106', '返还备件', '901', '/WebApp/ToolUseAction.do?method=backShow', NULL, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'90304', '报修修改', '903', NULL, NULL, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'90305', '报修删除', '903', NULL, NULL, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'90306', '已报修备件', '903', '/WebApp/ToolMainAction.do?method=showMainToolAll', NULL
, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'90406', '已送修备件', '904', '/WebApp/ToolToMainAction.do?method=showMainToolAll'
, NULL, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'50501', '查看施工信息', '505', '/WebApp/buildaction.do?method=getBuildInfo', NULL
, '1');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'40206', '删除', '402', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'30101', '查看割接申请', '301', '/WebApp/LineCutReAction.do?method=showAllRe', NULL
, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'30102', '添加割接申请', '301', '/WebApp/LineCutReAction.do?method=addShow', NULL
, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'30103', '高级查询', '301', '/WebApp/LineCutReAction.do?method=queryShow', NULL, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'30201', '查看割接审批', '302', '/WebApp/LineCutReAction.do?method=showAllAu', NULL
, '1');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'30202', '审批割接申请', '302', '/WebApp/LineCutReAction.do?method=auditShow', NULL
, '1');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'30203', '高级查询', '302', '/WebApp/LineCutReAction.do?method=queryShowForAu', NULL
, '1');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'30301', '查看施工信息', '303', '/WebApp/LineCutWorkAction.do?method=showAllWork'
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'30302', '添加施工信息', '303', '/WebApp/LineCutWorkAction.do?method=workShow', NULL
, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'30303', '高级查询', '303', '/WebApp/LineCutWorkAction.do?method=queryShowForWork'
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'30401', '查看归档', '304', '/WebApp/LineCutWorkAction.do?method=showAllAr', NULL
, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'30402', '割接归档', '304', '/WebApp/LineCutWorkAction.do?method=waitArShow', NULL
, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'30403', '高级查询', '304', '/WebApp/LineCutWorkAction.do?method=queryShowForAr', NULL
, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'30104', '修改割接申请', '301', NULL, NULL, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'30105', '删除割接申请', '301', NULL, NULL, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'72001', '查看人员', '720', '/WebApp/ConPersonAction.do?method=showConPerson', NULL
, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'72002', '增加人员', '720', '/WebApp/ConPersonAction.do?method=addConPersonShow', NULL
, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'72003', '高级查询', '720', '/WebApp/ConPersonAction.do?method=queryShow', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'72004', '修改人员', '720', NULL, NULL, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'72005', '删除人员', '720', NULL, NULL, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'50602', '填写验收信息', '506', '/WebApp/checkaction.do?method=getChangeInfo', NULL
, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'90107', '待还备件', '901', '/WebApp/ToolUseAction.do?method=shouldBackShow', NULL
, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70403', '修改用户组', '704', '/WebApp/UsergroupAction.do?method=loadEditFrom', NULL
, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70806', '设备初始化', '708', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70404', '修改用户组信息', '704', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'70405', '删除用户组信息', '704', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'72101', '查看光缆信息', '721', '/WebApp/CableSegmentAction.do?method=queryCableSegment'
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'72102', '增加光缆信息', '721', '/WebApp/CableSegmentAction.do?method=loadAddForm'
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'72103', '高级查询', '721', '/WebApp/CableSegmentAction.do?method=loadQueryForm', NULL
, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'72104', '修改光缆信息', '721', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'72105', '删除光缆信息', '721', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'30304', '修改施工信息', '303', NULL, NULL, '2');
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'50202', '填写勘查审定', '502', '/WebApp/changeapplyaction.do?method=getApplyInfoList&op=survey'
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'50203', '高级查询', '502', '/WebApp/changesurveyaction.do?method=loadQueryForm', NULL
, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'50204', '二次填写勘查', '502', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'50302', '填写准备信息', '503', '/WebApp/buildsetoutaction.do?method=listChangeInfo'
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'50303', '高级查询', '503', '/WebApp/buildsetoutaction.do?method=loadQueryForm', NULL
, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'50402', '填写委托信息', '504', '/WebApp/consignaction.do?method=listChangeInfo', NULL
, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'50403', '查询委托信息', '504', '/WebApp/consignaction.do?method=loadQueryForm', NULL
, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'50502', '填写施工信息', '505', '/WebApp/buildaction.do?method=getChangeInfo', NULL
, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'50503', '查询施工信息', '505', '/WebApp/buildaction.do?method=loadQueryForm', NULL
, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'50504', '修改', '505', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'50603', '查询验收信息', '506', '/WebApp/checkaction.do?method=loadQueryForm', NULL
, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'50701', '查看归档信息', '507', '/WebApp/pageonholeaction.do?method=getPageonholeList'
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'50702', '信息归档', '507', '/WebApp/pageonholeaction.do?method=getChangeInfoList'
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'50703', '查询归档信息', '507', '/WebApp/pageonholeaction.do?method=loadQueryForm'
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'50801', '查询修缮信息', '508', '/WebApp/stataction.do?method=loadQueryForm', NULL
, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'50802', '统计修缮信息', '508', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'50304', '修改', '503', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'50404', '修改', '504', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'30601', '查看割接验收', '306', '/WebApp/LineCutAcceptAction.do?method=showAllAcc'
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'30602', '验收割接', '306', '/WebApp/LineCutAcceptAction.do?method=showAllWorkForAcc'
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'30603', '查询割接验收', '306', '/WebApp/LineCutAcceptAction.do?method=showAccQuery'
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'110101', '查看派单', '1101', '/WebApp/SendTaskAction.do?method=showAllSendTask', NULL
, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'110102', '指派任务', '1101', '/WebApp/SendTaskAction.do?method=showSendTask', NULL
, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'110103', '高级查询', '1101', '/WebApp/SendTaskAction.do?method=showQuerySendTask'
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'110104', '派单修改', '1101', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'110201', '查看签收', '1102', '/WebApp/EndorseAction.do?method=showAllEndorse', NULL
, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'110202', '签收任务', '1102', '/WebApp/EndorseAction.do?method=showTaskToEndorse'
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'110203', '高级查询', '1102', '/WebApp/EndorseAction.do?method=showQueryEndorse', NULL
, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'110301', '查看回复', '1103', '/WebApp/ReplyAction.do?method=showAllReply', NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'110302', '回复任务', '1103', '/WebApp/ReplyAction.do?method=showTaskToReply', NULL
, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'110303', '高级查询', '1103', '/WebApp/ReplyAction.do?method=showQueryReply', NULL
, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'110304', '修改回复', '1103', NULL, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'110401', '查看验证', '1104', '/WebApp/ValidateAction.do?method=showAllValidate', NULL
, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'110402', '验证任务', '1104', '/WebApp/ValidateAction.do?method=showTaskToValidate'
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'110403', '高级查询', '1104', '/WebApp/ValidateAction.do?method=showQueryValidate'
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'80404', '入库统计', '804', '/WebApp/PartStockAction.do?method=queryShowForStat', NULL
, NULL);

INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'80504', '入库统计', '805', '/WebApp/PartStockAction.do?method=queryShowForOldStat'
, NULL, NULL);
INSERT INTO SONMENU ( ID, LABLENAME, PARENTID, HREFURL, REMARK, TYPE ) VALUES (
'50704', '结算付款', '507', '/WebApp/pageonholeaction.do?method=showSquare', NULL
, NULL);
commit;

INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'507', '修缮归档', NULL, '5', NULL, NULL, 7, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'508', '查询统计', NULL, '5', NULL, NULL, 8, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'201', '年巡检计划', NULL, '2', NULL, NULL, 1, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'202', '月巡检计划', NULL, '2', NULL, NULL, 2, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'203', '周巡检计划', NULL, '2', NULL, NULL, 3, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'205', '巡检计划审批', NULL, '2', NULL, NULL, 5, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'204', '自定义计划', NULL, '2', NULL, NULL, 4, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'701', '区域管理', NULL, '7', NULL, NULL, 1, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'702', '部门管理', NULL, '7', NULL, NULL, 2, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'703', '代维单位管理', NULL, '7', NULL, NULL, 3, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'704', '用户组管理', NULL, '7', NULL, NULL, 4, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'705', '用户管理', NULL, '7', NULL, NULL, 5, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'707', '巡检员管理', NULL, '7', NULL, NULL, 7, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'708', '巡检设备管理', NULL, '7', NULL, NULL, 8, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'709', '巡检线路管理', NULL, '7', NULL, NULL, 9, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'710', '巡检线段管理', NULL, '7', NULL, NULL, 10, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'711', '巡检点管理', NULL, '7', NULL, NULL, 11, '9');
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'716', '系统日志管理', NULL, '7', NULL, NULL, 16, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'206', '巡检明细表', NULL, '2', NULL, NULL, 6, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'207', '漏检明细表', NULL, '2', NULL, NULL, 7, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'208', '计划巡检率', NULL, '2', NULL, NULL, 8, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'209', '计划审批通过率', NULL, '2', NULL, NULL, 9, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'210', '计划汇总报表', NULL, '2', NULL, NULL, 10, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'401', '盯防点管理', NULL, '4', NULL, NULL, 1, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'301', '割接申请管理', NULL, '3', NULL, NULL, 1, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'501', '修缮申请', NULL, '5', NULL, NULL, 1, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'506', '修缮验收', NULL, '5', NULL, NULL, 6, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'712', '口令修改', NULL, '7', NULL, NULL, 12, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'713', '巡检事故码管理', NULL, '7', NULL, NULL, 13, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'714', '巡检操作管理', NULL, '7', NULL, NULL, 14, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'715', '报警号码管理', NULL, '7', NULL, NULL, 15, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'101', '实时监控', NULL, '1', NULL, NULL, 1, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'602', '故障处理', NULL, '6', NULL, NULL, 2, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'601', '隐患处理', NULL, '6', NULL, NULL, 1, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'302', '割接审批管理', NULL, '3', NULL, NULL, 2, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'717', '短信日志管理', NULL, '7', NULL, NULL, 17, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'718', '察看在线用户', NULL, '7', NULL, NULL, 18, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'706', '巡检维护组管理', NULL, '7', NULL, NULL, 6, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'402', '盯防管理', NULL, '4', NULL, NULL, 2, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'719', '短信活动时段', NULL, '7', NULL, NULL, 19, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'801', '材料申请管理', NULL, '8', NULL, NULL, 1, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'802', '材料审批管理', NULL, '8', NULL, NULL, 2, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'803', '材料使用管理', NULL, '8', NULL, NULL, 3, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'804', '材料入库管理', NULL, '8', NULL, NULL, 4, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'805', '利旧材料管理', NULL, '8', NULL, NULL, 5, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'806', '库存材料管理', NULL, '8', NULL, NULL, 6, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'807', '维护材料信息', NULL, '8', NULL, NULL, 7, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'901', '备件领还管理', NULL, '9', NULL, NULL, 1, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'502', '勘查审定', NULL, '5', NULL, NULL, 2, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'903', '备件报修管理', NULL, '9', NULL, NULL, 3, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'904', '备件送修管理', NULL, '9', NULL, NULL, 4, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'905', '备件入库管理', NULL, '9', NULL, NULL, 5, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'906', '备件报废管理', NULL, '9', NULL, NULL, 6, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'907', '备件库存管理', NULL, '9', NULL, NULL, 7, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'908', '备件基本信息', NULL, '9', NULL, NULL, 8, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'720', '单位人员管理', NULL, '7', NULL, NULL, 20, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'303', '割接施工管理', NULL, '3', NULL, NULL, 3, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'304', '割接归档管理', NULL, '3', NULL, NULL, 4, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'305', '割接查询统计', NULL, '3', NULL, NULL, 5, '9');
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'403', '盯防统计', NULL, '4', NULL, NULL, 3, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'503', '施工准备', NULL, '5', NULL, NULL, 3, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'504', '施工委托', NULL, '5', NULL, NULL, 4, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'505', '施工信息', NULL, '5', NULL, NULL, 5, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'721', '光缆信息管理', NULL, '7', NULL, NULL, 7, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'306', '割接验收管理', NULL, '3', NULL, NULL, 9, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'1101', '指派任务', NULL, '11', NULL, NULL, 1, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'1102', '签收任务', NULL, '11', NULL, NULL, 2, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'1103', '回复任务', NULL, '11', NULL, NULL, 3, NULL);
INSERT INTO SUBMENU ( ID, LABLENAME, HREFURL, PARENTID, REMARK, REGIONID, SHOWNO,
TYPE ) VALUES (
'1104', '验证任务', NULL, '11', NULL, NULL, 4, NULL);
commit;

INSERT INTO SYSDICTIONARY ( VALUE, LABLE, TYPE, MAXSIZE, STATE, TABLES,
REMARK ) VALUES (
'00000004', '密码有效期验证期限', NULL, 0, NULL, NULL, 'maxsize的值必须进行设置，如果Maxsize的值为0 表示系统将不对其进行密码期限验证；若maxsize的值大于0要求系统对其进行密码有效期验证，密码有效期一天为计算单位');
INSERT INTO SYSDICTIONARY ( VALUE, LABLE, TYPE, MAXSIZE, STATE, TABLES,
REMARK ) VALUES (
'00000003', '是否给目标处理人发送短信', '1', NULL, NULL, NULL, '有新的申请或审批情况时是否给目标处理人或申请人发送短信,当type值为"1"时，给目标处理人发送短信。当type值为"0"或为null时，则反之。');
INSERT INTO SYSDICTIONARY ( VALUE, LABLE, TYPE, MAXSIZE, STATE, TABLES,
REMARK ) VALUES (
'00000001', '巡检人员管理方式', '1', NULL, NULL, NULL, '该条记录是关于巡检人员的配置.当type值为"1"时,巡检人员按组进行管理,当type值为"0"或为null时,巡检人员是按人进行管理,即一个设备对应');
INSERT INTO SYSDICTIONARY ( VALUE, LABLE, TYPE, MAXSIZE, STATE, TABLES,
REMARK ) VALUES (
'00000002', '是否显示光缆信息', '1', NULL, NULL, NULL, '是否显示光缆信息的配置.当type值为"1"时,显示光缆信息.当type值为"0"或为null时,不显示光缆信息');
commit;
INSERT INTO MAINMODULEMENU ( ID, LABLENAME, IMGURL, HREFURL, REMARK,
SHOWNO ) VALUES (
'2', '巡检管理', '../images/iconmenu/xjjhgl.gif', NULL, NULL, 2);
INSERT INTO MAINMODULEMENU ( ID, LABLENAME, IMGURL, HREFURL, REMARK,
SHOWNO ) VALUES (
'1', '实时监控', '../images/iconmenu/ssjk.gif', NULL, NULL, 1);
INSERT INTO MAINMODULEMENU ( ID, LABLENAME, IMGURL, HREFURL, REMARK,
SHOWNO ) VALUES (
'4', '盯防管理', '../images/iconmenu/sdgl.gif', NULL, NULL, 4);
INSERT INTO MAINMODULEMENU ( ID, LABLENAME, IMGURL, HREFURL, REMARK,
SHOWNO ) VALUES (
'5', '修缮管理', '../images/iconmenu/xlgjgl.gif', NULL, NULL, 5);
INSERT INTO MAINMODULEMENU ( ID, LABLENAME, IMGURL, HREFURL, REMARK,
SHOWNO ) VALUES (
'7', '系统管理', '../images/iconmenu/xtgl.gif', NULL, NULL, 9);
INSERT INTO MAINMODULEMENU ( ID, LABLENAME, IMGURL, HREFURL, REMARK,
SHOWNO ) VALUES (
'6', '故障管理', '../images/iconmenu/xlqggl.gif', NULL, NULL, 6);
INSERT INTO MAINMODULEMENU ( ID, LABLENAME, IMGURL, HREFURL, REMARK,
SHOWNO ) VALUES (
'8', '材料管理', '../images/iconmenu/bpbjybgl.gif', NULL, NULL, 7);
INSERT INTO MAINMODULEMENU ( ID, LABLENAME, IMGURL, HREFURL, REMARK,
SHOWNO ) VALUES (
'9', '备件管理', '../images/iconmenu/jczlgl.gif', NULL, NULL, 8);
INSERT INTO MAINMODULEMENU ( ID, LABLENAME, IMGURL, HREFURL, REMARK,
SHOWNO ) VALUES (
'3', '割接管理', '../images/iconmenu/xjsjcjsz.gif', NULL, NULL, 3);
INSERT INTO MAINMODULEMENU ( ID, LABLENAME, IMGURL, HREFURL, REMARK,
SHOWNO ) VALUES (
'11', '派单管理', '../images/iconmenu/xjsjcjsz.gif', NULL, NULL, 13);
commit;

--用户数据
INSERT INTO DEPTINFO ( DEPTID, DEPTNAME, LINKMANINFO, PARENTID, PARENTNAME, REGIONID, REMARK, STATE,
ONCREATE, ONUPDATE, ONDELETE ) VALUES (
'0000', '云南移动', '联系人', ' ', '中国移动', '530000', '备注', NULL,  TO_Date( '03/17/2006 10:37:25 上午', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL);
INSERT INTO REGION ( REGIONNAME, REGIONID, REGIONDES, STATE, PARENTREGIONID, LEFTPOINT, RIGHTPOINT,
IP, MAPURL, ONCREATE, ONUPDATE, ONDELETE ) VALUES (
'云南省', ' 530000', '区域描述', NULL, '000000', NULL, NULL, NULL, NULL,  TO_Date( '03/17/2006 10:37:25 上午', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL);
INSERT INTO USERGROUPMASTER ( ID, GROUPNAME, REGIONID, REMARK ) VALUES (
'00000', '系统管理员', '510000', '系统管理员');

INSERT INTO USERINFO ( USERNAME, USERID, DEPTID, REGIONID, PASSWORD, ACCOUNTTERM,
 ACCOUNTSTATE,DEPTYPE, ACCIDENTTIME, ONLINEMANTIME, WATCHTIME) VALUES (
'初始用户', 'admin', '0000', '530000', 'admin', TO_Date( '12/30/2006 12:00:00 上午', 'MM/DD/YYYY HH:MI:SS AM')
, '1', '1', '24'
, '2', '72');
INSERT INTO USERGOURPUSERLIST ( ID, USERID, USERGROUPID, REMARK ) VALUES (
'00000000000000000001', 'admin', '00000', NULL);
INSERT INTO USERGROUPMOUDULELIST ( ID, USERGROUPID, SONMENUID,
REMARK ) VALUES (
'00000000000000000001', '00000', '70502', NULL);
INSERT INTO USERGROUPMOUDULELIST ( ID, USERGROUPID, SONMENUID,
REMARK ) VALUES (
'00000000000000000002', '00000', '70402', NULL);
INSERT INTO USERGROUPMOUDULELIST ( ID, USERGROUPID, SONMENUID,
REMARK ) VALUES (
'00000000000000000003', '00000', '70403', NULL);
INSERT INTO USERGROUPMOUDULELIST ( ID, USERGROUPID, SONMENUID,
REMARK ) VALUES (
'00000000000000000004', '00000', '70401', NULL);
commit;


INSERT INTO REGION ( REGIONNAME, REGIONID, REGIONDES, PARENTREGIONID, ONCREATE) VALUES ( 
'云南省', '530000', '', '000000', sysdate); 
INSERT INTO REGION ( REGIONNAME, REGIONID, REGIONDES, PARENTREGIONID, ONCREATE) VALUES ( 
' 文山', '532600', '', '530000', sysdate); 
INSERT INTO REGION ( REGIONNAME, REGIONID, REGIONDES, PARENTREGIONID, ONCREATE) VALUES ( 
'昭通市', '530600', '', '530000', sysdate); 
INSERT INTO REGION ( REGIONNAME, REGIONID, REGIONDES, PARENTREGIONID, ONCREATE) VALUES ( 
'玉溪市', '530400', '', '530000', sysdate); 
INSERT INTO REGION ( REGIONNAME, REGIONID, REGIONDES, PARENTREGIONID, ONCREATE) VALUES ( 
'昆明市', '530100', '', '530000', sysdate); 
INSERT INTO REGION ( REGIONNAME, REGIONID, REGIONDES, PARENTREGIONID, ONCREATE) VALUES ( 
'楚雄', '532300', '', '530000', sysdate); 
INSERT INTO REGION ( REGIONNAME, REGIONID, REGIONDES, PARENTREGIONID, ONCREATE) VALUES ( 
'大理', '532900', '', '530000', sysdate); 
INSERT INTO REGION ( REGIONNAME, REGIONID, REGIONDES, PARENTREGIONID, ONCREATE) VALUES ( 
'云南省', '530000', '', '530000', sysdate); 
INSERT INTO REGION ( REGIONNAME, REGIONID, REGIONDES, PARENTREGIONID, ONCREATE) VALUES ( 
'思茅市', '532700', '', '530000', sysdate); 
INSERT INTO REGION ( REGIONNAME, REGIONID, REGIONDES, PARENTREGIONID, ONCREATE) VALUES ( 
'红河', '532500', '', '530000', sysdate); 
INSERT INTO REGION ( REGIONNAME, REGIONID, REGIONDES, PARENTREGIONID, ONCREATE) VALUES ( 
'临沧市', '530900', '', '530000', sysdate); 

INSERT INTO REGION ( REGIONNAME, REGIONID, REGIONDES, PARENTREGIONID, ONCREATE) VALUES ( 
'曲靖市', '530300', '', '530000', sysdate); 
INSERT INTO REGION ( REGIONNAME, REGIONID, REGIONDES, PARENTREGIONID, ONCREATE) VALUES ( 
'怒江', '533300', '', '530000', sysdate); 
INSERT INTO REGION ( REGIONNAME, REGIONID, REGIONDES, PARENTREGIONID, ONCREATE) VALUES ( 
'保山市', '530500', '', '530000', sysdate); 
INSERT INTO REGION ( REGIONNAME, REGIONID, REGIONDES, PARENTREGIONID, ONCREATE) VALUES ( 
'迪庆市', '533400', '', '530000', sysdate); 
INSERT INTO REGION ( REGIONNAME, REGIONID, REGIONDES, PARENTREGIONID, ONCREATE) VALUES ( 
'西双市', '532800', '', '530000', sysdate); 
INSERT INTO REGION ( REGIONNAME, REGIONID, REGIONDES, PARENTREGIONID, ONCREATE) VALUES ( 
'丽江市', '530700', '', '530000', sysdate); 
INSERT INTO REGION ( REGIONNAME, REGIONID, REGIONDES, PARENTREGIONID, ONCREATE) VALUES ( 
'德宏市', '533100', '', '530000', sysdate); 
commit;
