--在云南制定计划时增加对任务巡检点总数进行评估
ALTER TABLE TASKINFO
 ADD (EVALUATEPOINT  VARCHAR2(10 BYTE)  DEFAULT 0);
ALTER TABLE SUBTASK_STENCIL
 ADD (EVALUATEPOINT  VARCHAR2(10 BYTE)  DEFAULT 0);

--年月计划表中增加主键
ALTER TABLE YEARMONTHPLAN
 ADD PRIMARY KEY
 (ID);