
--2009-11-23 杨隽 修缮管理表重命名
rename linepatrol_remedy to lp_remedy;
rename linepatrol_remedyitem to lp_remedyitem;
rename linepatrol_remedyitem_type to lp_remedyitem_type;
rename linepatrol_remedy_accept to lp_remedy_accept;
rename linepatrol_remedy_attach to lp_remedy_attach;
rename linepatrol_remedy_balance to lp_remedy_balance;
rename linepatrol_remedy_bal_item to lp_remedy_bal_item;
rename linepatrol_remedy_bal_material to lp_remedy_bal_material;
rename linepatrol_remedy_item to lp_remedy_item;
rename linepatrol_remedy_material to lp_remedy_material;
rename linepatrol_remedy_material_upd to lp_remedy_material_upd;
rename linepatrol_remedy_status to lp_remedy_status;
rename linepatrol_remedy_steps to lp_remedy_steps;
rename linepatrol_remedy_strike to lp_remedy_strike;
rename linepatrol_remedy_try_item to lp_remedy_try_item;
rename linepatrol_remedy_workflow to lp_remedy_workflow;

